[workspace]

members = [
    "espa-bitops",
    "espa-codecs",
]

[package]
name = "entropy-sparrow"
version = "0.1.0"
edition = "2024"

[dependencies]
espa-bitops = { path = "espa-bitops" }
espa-codecs = { path = "espa-codecs" }

[[bin]]
name = "espa"
path = "main.rs"
