name: cargo-test-suite
on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testrunner:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025, macos-13, macos-15]

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Remove preinstalled Rust tools
        run: rm -f ~/.cargo/bin/rustfmt ~/.cargo/bin/cargo-fmt ~/.cargo/bin/rust-analyzer
      
      - name: Upgrade Rust toolchain
        run: rustup update ${{ env.RUST_TOOLCHAIN }} && rustup default ${{ env.RUST_TOOLCHAIN }}

      - name: Dump toolchain versions
        run: |
          echo "Enabled Rust toolchain:"
          rustup show active-toolchain
          rustc --version
          cargo --version

      - name: Run cargo tests (without sanitizers)
        run: cargo test --all-features --all-targets --workspace
